
2019.11.05 14:37	HTTPSConnectionPool(host='data.gateio.co', port=443): Max retries exceeded with url: /api2/1/ticker/btc_usdt (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f58a263a5f8>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2019.11.05 18:35	HTTPSConnectionPool(host='data.gateio.co', port=443): Max retries exceeded with url: /api2/1/ticker/btc_usdt (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f58a2cdd7f0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2019.11.06 09:35	HTTPSConnectionPool(host='data.gateio.co', port=443): Max retries exceeded with url: /api2/1/ticker/btc_usdt (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f58a2cdd518>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2019.11.06 09:36	HTTPSConnectionPool(host='data.gateio.co', port=443): Max retries exceeded with url: /api2/1/ticker/btc_usdt (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f58a2cdd2b0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2019.11.06 09:44	HTTPSConnectionPool(host='data.gateio.co', port=443): Max retries exceeded with url: /api2/1/ticker/btc_usdt (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f58a2cdd860>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2019.11.07 17:31	HTTPSConnectionPool(host='data.gateio.co', port=443): Max retries exceeded with url: /api2/1/ticker/btc_usdt (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f58a2cddeb8>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2019.11.07 21:08	HTTPSConnectionPool(host='data.gateio.co', port=443): Max retries exceeded with url: /api2/1/ticker/btc_usdt (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f58a2cb3630>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2019.11.09 18:14	HTTPSConnectionPool(host='data.gateio.co', port=443): Max retries exceeded with url: /api2/1/ticker/btc_usdt (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f58a2cddfd0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2019.11.09 19:09	HTTPSConnectionPool(host='data.gateio.co', port=443): Max retries exceeded with url: /api2/1/ticker/btc_usdt (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f58a2cdde80>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2019.11.09 19:13	HTTPSConnectionPool(host='data.gateio.co', port=443): Max retries exceeded with url: /api2/1/ticker/btc_usdt (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f58a263a7f0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2019.11.09 21:56	HTTPSConnectionPool(host='data.gateio.co', port=443): Max retries exceeded with url: /api2/1/ticker/btc_usdt (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f58a2cdd748>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2019.11.10 09:27	HTTPSConnectionPool(host='data.gateio.co', port=443): Max retries exceeded with url: /api2/1/ticker/btc_usdt (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f58a2630c88>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2019.11.10 12:45	HTTPSConnectionPool(host='data.gateio.co', port=443): Max retries exceeded with url: /api2/1/ticker/btc_usdt (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f58a2cdd5f8>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2019.11.10 13:18	HTTPSConnectionPool(host='data.gateio.co', port=443): Max retries exceeded with url: /api2/1/ticker/btc_usdt (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f58a263a160>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2019.11.10 13:23	HTTPSConnectionPool(host='data.gateio.co', port=443): Max retries exceeded with url: /api2/1/ticker/btc_usdt (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f58a2cdd208>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2019.11.10 15:47	HTTPSConnectionPool(host='data.gateio.co', port=443): Max retries exceeded with url: /api2/1/ticker/btc_usdt (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f58a2cdd780>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2019.11.10 16:03	HTTPSConnectionPool(host='data.gateio.co', port=443): Max retries exceeded with url: /api2/1/ticker/btc_usdt (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f58a2630198>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2019.11.12 23:19	HTTPSConnectionPool(host='data.gateio.co', port=443): Max retries exceeded with url: /api2/1/ticker/btc_usdt (Caused by SSLError(SSLError("bad handshake: SysCallError(-1, 'Unexpected EOF')")))
2019.11.13 01:20	HTTPSConnectionPool(host='data.gateio.co', port=443): Max retries exceeded with url: /api2/1/ticker/btc_usdt (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f58a2cbd320>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2019.11.13 03:25	HTTPSConnectionPool(host='data.gateio.co', port=443): Max retries exceeded with url: /api2/1/ticker/btc_usdt (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f58a2633eb8>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2019.11.13 08:11	HTTPSConnectionPool(host='data.gateio.co', port=443): Max retries exceeded with url: /api2/1/ticker/btc_usdt (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f58a2633400>: Failed to establish a new connection: [Errno 110] Connection timed out'))
2019.11.13 09:43	HTTPSConnectionPool(host='data.gateio.co', port=443): Max retries exceeded with url: /api2/1/ticker/btc_usdt (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f58a2633a20>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2019.11.13 15:08	HTTPSConnectionPool(host='data.gateio.co', port=443): Max retries exceeded with url: /api2/1/ticker/btc_usdt (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f58a2cdd5f8>: Failed to establish a new connection: [Errno -2] Name or service not known'))